### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by guandeng** [i161079/Tensorflow_tfrecords_train#1]
怎么用呢？可以写个说明吗

**Comment by lipstick-49** [comment]
使用
![tim 20180407223041](https://user-images.githubusercontent.com/17353956/38456131-719958ba-3ab3-11e8-9333-34ce98c4480d.png)
创建tfrecords文件
file_dir = ''填写数据集目录
file_dir目录下是每个图像的分类放正一个目录里
例如：
file_dir = 'F:\data\train'
![image](https://user-images.githubusercontent.com/17353956/38456182-11713204-3ab4-11e8-8e5a-6902b04afe44.png)
